pfcp-address: "10.0.60.3"
control:
  uri: "http://192.0.2.2:8080"
  bind-addr: "192.0.2.2:8080"
logger:
  level: info
uplink:
  - control-uri: "http://[fd00:0:0:0:2:8000:0:2]:8080"
    enabled: true
    area:
      - "10.0.0.1/32" # gnb1
      - "10.0.0.2/32" # gnb2
    service: "10.4.0.1"
    segments-list:
      - "fc00:2:1::"
  - control-uri: "http://[fd00:0:0:0:2:8000:0:2]:8080"
    enabled: false
    area:
      - "10.0.0.1/32" # gnb1
      - "10.0.0.2/32" # gnb2
    service: "10.4.0.1"
    segments-list:
      - "fc00:3:1::"
downlink:
  - control-uri: "http://[fd00:0:0:0:2:8000:0:4]:8080"
    enabled: true
    area:
      - "10.0.0.1/32" # gnb1
      - "10.0.0.2/32" # gnb2
    srgw-gtp4: "10.3.0.1"
    segments-list:
      - "fc00:1:1::/48"
  - control-uri: "http://[fd00:0:0:0:2:8000:0:5]:8080"
    enabled: true
    area:
      - "10.0.0.1/32" # gnb1
      - "10.0.0.2/32" # gnb2
    srgw-gtp4: "10.3.0.1"
    segments-list:
      - "fc00:1:1::/48"
